### PR TITLE
add index.js

### PR DESCRIPTION
**Pull request by ian-antking**
I added an index.js

### CODE REVIEW

**Comment by SanMasood** [comment]
Awesome work!

**Comment by EveRefi** [comment]
just wow!

**Comment by markrea** [comment]
unreal typing!

**Comment by jdsandahl** [comment]
Well done :)

**Comment by TimmyDDthe1st** [comment]
don't do it! you'll launch the nukes!

**Comment by joewarnerhigham** [comment]
:)

**Comment by anywhereiromy** [comment]
GREAT

**Comment by doriancretu** [comment]
nice

**Pull request merged**
